spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${AUCTION_QUERY_DB_URL:${SPRING_DATASOURCE_URL}}
spring.datasource.username=${AUCTION_QUERY_DB_USERNAME:${SPRING_DATASOURCE_USERNAME}}
spring.datasource.password=${AUCTION_QUERY_DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}
spring.jpa.hibernate.ddl-auto=none
