spring.datasource.url=${AUCTION_QUERY_DB_URL}
spring.datasource.username=${AUCTION_QUERY_DB_USERNAME}
spring.datasource.password=${AUCTION_QUERY_DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=${AUCTION_QUERY_DB_POOL_SIZE:5}
spring.jpa.hibernate.ddl-auto=none
